### ISSUE TITLE
Deployment Tracker Service is discontinued

### ISSUE THREAD

**Issue by ptitzler** [IBM-Bluemix/insurance-orders#12]
Please refer to the following document for details and migration instructions https://github.com/IBM-Bluemix/cf-deployment-tracker-client-node/wiki/migrating-to-the-new-metrics-tracker-client.

P.S. Your app is currently configured to require the latest version of the DTC for Node.js. This version no longer submits tracking requests.

**Comment by uwefassnacht** [comment]
Bluemix [toolchain](https://console.bluemix.net/devops/toolchains/4811990e-3862-415d-b259-9b453e97247a "insurance-toolchain-eu"): [Delivery Pipeline](https://console.bluemix.net/devops/pipelines/a2542e6f-ecc3-4932-ad42-9963ce8ebaab "orders (master)") deployed [insurance-orders](https://github.com/IBM-Bluemix/insurance-orders/releases/tag/deploy-ibm-yp-eu-gb-uwe.fassnacht-de.ibm.com-cloudco-20171208-094852 "deploy-ibm-yp-eu-gb-uwe.fassnacht-de.ibm.com-cloudco-20171208-094852") to [cloudco](https://console.bluemix.net/apps/6430b0f0-b67d-4fb1-b2b2-fc660b06422c?env_id=ibm:yp:eu-gb "ibm:yp:eu-gb:uwe.fassnacht@de.ibm.com:cloudco"), including commit b90e38684a3f171ea8b73a7cd4662ad6595154e9

**Comment by ptitzler** [comment]
Thank you!
